from sqlalchemy.orm import Session

from app.models.remediation import Remediation


def find_approved_remediation(
    db: Session,
    remediation_action: str,
) -> Remediation | None:
    """
    Find an enabled and approved remediation for the
    canonical remediation action generated by the LLM.
    """

    return (
        db.query(Remediation)
        .filter(
            Remediation.remediation_action == remediation_action,
            Remediation.approved.is_(True),
            Remediation.enabled.is_(True),
        )
        .first()
    )