"use client";

import { useMemo, useState } from "react";
import { useInvestigationStore } from "@/lib/store";
import { PageHeader, Card, Button, CodeBlock, EmptyState } from "./ui/primitives";
import { SourceBadge, RiskBadge } from "./ui/badge";
import { formatDate } from "@/lib/format";

export default function Playbooks({
  onOpenIncidents,
}: {
  onOpenIncidents: () => void;
}) {
  const { playbooks } = useInvestigationStore();
  const [expanded, setExpanded] = useState<string | null>(null);

  const sorted = useMemo(
    () => [...playbooks].sort((a, b) => b.createdAt - a.createdAt),
    [playbooks],
  );

  return (
    <section className="h-full overflow-y-auto">
      <div className="mx-auto max-w-5xl px-8 py-8">
        <PageHeader
          title="Playbooks"
          description="Playbooks retrieved or generated by the agent during real investigations."
        />

        {sorted.length === 0 ? (
          <EmptyState
            icon="playbook"
            title="No playbooks yet"
            description="Run an AI investigation on an incident and the playbook it retrieves or generates will appear here automatically."
            action={<Button icon="activity" variant="secondary" onClick={onOpenIncidents}>Open Incidents</Button>}
          />
        ) : (
          <div className="space-y-4">
            {sorted.map((pb) => {
              const isOpen = expanded === pb.key;
              return (
                <Card key={pb.key} className="overflow-hidden">
                  <button type="button" onClick={() => setExpanded(isOpen ? null : pb.key)} className="w-full text-left">
                    <div className="flex items-start justify-between gap-4 px-5 py-4 hover:bg-[var(--surface-subtle)]">
                      <div className="min-w-0">
                        <div className="truncate text-sm font-medium text-[var(--text)]">{pb.remediationAction}</div>
                        <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-[var(--text-muted)]">
                          <SourceBadge value={pb.source} />
                          <RiskBadge value={pb.riskLevel} />
                          <span>· {pb.incidentTitle}</span>
                          {pb.targetGroup && <span>· group: {pb.targetGroup}</span>}
                          <span>· {formatDate(new Date(pb.createdAt).toISOString())}</span>
                        </div>
                      </div>
                      <span className={`mt-1 text-[var(--text-muted)] transition-transform ${isOpen ? "rotate-180" : ""}`}>
                        ▾
                      </span>
                    </div>
                  </button>
                  {isOpen && (
                    <div className="border-t border-[var(--border)] p-4">
                      <CodeBlock
                        value={pb.playbook}
                        label={pb.source === "rag" ? "retrieved-playbook.yaml" : "generated-playbook.yaml"}
                      />
                    </div>
                  )}
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </section>
  );
}