"""update remediations

Revision ID: 0e4b5d355169
Revises: 37f05d008739
Create Date: 2026-08-25 20:59:52.844925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4b5d355169'
down_revision: Union[str, Sequence[str], None] = '37f05d008739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediations', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
