"""update remediation action identifier

Revision ID: 37f05d008739
Revises: ac739cd263c0
Create Date: 2026-08-23 13:49:20.682338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f05d008739'
down_revision: Union[str, Sequence[str], None] = 'ac739cd263c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('remediation_action', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_remediations_remediation_action'), 'remediations', ['remediation_action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediations_remediation_action'), table_name='remediations')
    op.drop_column('remediations', 'remediation_action')
    # ### end Alembic commands ###
