"""add incident lifecycle fields

Revision ID: 3e1fa6428b37
Revises: d157cb6cb4a6
Create Date: 2026-08-15 18:45:30.322670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1fa6428b37'
down_revision: Union[str, Sequence[str], None] = 'd157cb6cb4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('current_phase', sa.String(length=50), nullable=False))
    op.add_column('incidents', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'updated_at')
    op.drop_column('incidents', 'verification_status')
    op.drop_column('incidents', 'resolution')
    op.drop_column('incidents', 'root_cause')
    op.drop_column('incidents', 'current_phase')
    # ### end Alembic commands ###
