"""add playbook filename to remediations

Revision ID: 510fbc61cadd
Revises: 0e4b5d355169
Create Date: 2026-09-03 10:44:57.234019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510fbc61cadd'
down_revision: Union[str, Sequence[str], None] = '0e4b5d355169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('playbook_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediations', 'playbook_filename')
    # ### end Alembic commands ###
