"""add remediations table

Revision ID: ac739cd263c0
Revises: 53ca733cb884
Create Date: 2026-08-23 13:05:17.230232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac739cd263c0'
down_revision: Union[str, Sequence[str], None] = '53ca733cb884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('playbook', sa.Text(), nullable=False),
    sa.Column('target_group', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_table('remediations')
    # ### end Alembic commands ###
